import { Inter } from "next/font/google";
import "./globals.css";
import Shapes from "@/components/Shapes";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import StoreProvider from "./StoreProvider";
import MainLayout from "./MainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative bg-gray-800 text-white`}>
        <StoreProvider>
          <Header />
          <MainLayout>{children}</MainLayout>
          <Footer />
          <div className="fixed inset-0 -z-10 flex items-center justify-center ">
            <Shapes />
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
