import { Inter } from "next/font/google";
import "./globals.css";
import Shapes from "@/components/Shapes";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <StoreProvider>
          <Header />
          {children}
          <Footer />
          <div className="fixed top-0 left-0 -z-10 w-screen h-screen flex items-center justify-center ">
            <Shapes />
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
